# -*- coding: utf-8 -*-
"""ChromaDB tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rbio2NFwQdNRU79EoHas37f3Jl8iM8Q-
"""

!pip install chromadb sentence-transformers

import chromadb
import os
os.environ['ALLOW_RESET'] = "True"
from sentence_transformers import SentenceTransformer

# load a embeddings model from SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)

# Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)

# Formatting the output for a clear view
for idx_i, sentence1 in enumerate(sentences):
    print(sentence1)
    for idx_j, sentence2 in enumerate(sentences):
        print(f" - {sentence2: <30}: {similarities[idx_i][idx_j]:.4f}")

chroma_client = chromadb.Client() # load the chromadb client

collection = chroma_client.create_collection(name="my_collection") # create a collection that will store vectors

# Add data to collection
collection.add(
    documents=[
        "This is a document about pineapple",
        "This is a document about oranges"
    ],
    ids=["id1", "id2"]
)

# Querying on the vectordb
results = collection.query(
    query_texts=["This is a query document about hawaii"], # Chroma will embed this for you
    n_results=2 # how many results to return
)

print(results)

# The embeddings are included in the output because it is a very big vector.
collection.get(include=['embeddings'])

"""### Persistent storage"""

# Data will be persisted automatically and loaded on start (if it exists).
client = chromadb.PersistentClient(path="/content/my_chroma_db")

client.heartbeat() # returns a nanosecond heartbeat. Useful for making sure the client remains connected.

client.reset() # Empties and completely resets the database. ⚠️ This is destructive and not reversible.

from chromadb.utils import embedding_functions
sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

# To pass an embedding function to the vectordb use embedding_function
collection = client.get_or_create_collection(name="my_collection_2", embedding_function=sentence_transformer_ef)

print(collection.peek()) # returns a list of the first 10 items in the collection

print(collection.count()) # returns the number of items in the collection

print(collection.modify(name="vect-db")) # Rename the collection

# create_collection also takes an optional metadata argument which can be used to customize the distance method
# of the embedding space by setting the value of hnsw:space
collection = client.create_collection(
        name="KnowledgeBase",
        metadata={"hnsw:space": "cosine"} # l2 is the default
    )

collection.add(
    documents=["lorem ipsum...", "doc2", "doc3",],
    metadatas=[{"chapter": "3", "verse": "16"}, {"chapter": "3", "verse": "5"}, {"chapter": "29", "verse": "11"}],
    ids=["id1", "id2", "id3"]
)

collection.peek()

collection.count() # count no. of documents added

"""You can also store documents elsewhere, and just supply a list of embeddings and metadata to Chroma. You can use the ids to associate the embeddings with your documents stored elsewhere.


"""

collection = client.create_collection(name="Test1", embedding_function=sentence_transformer_ef)

collection.add(
    embeddings=[[1.1, 2.3, 3.2], [4.5, 6.9, 4.4], [1.1, 2.3, 3.2]],
    metadatas=[{"chapter": "3", "verse": "16"}, {"chapter": "3", "verse": "5"}, {"chapter": "29", "verse": "11"}],
    ids=["id1", "id2", "id3"]
)

collection.query(
    query_embeddings=[[11.1, 12.1, 13.1]],
    n_results=10,
)

# items can also be retrieved from a collection using get

collection.get(
	ids=["id1", "id2", "id3"],
	where={"style": "style1"}
)

collection.query(
    query_embeddings=[[11.1, 12.1, 13.1]],
    n_results=10,
    where={"chapter": "3"}
)

# $eq - equal to (string, int, float)
# $ne - not equal to (string, int, float)
# $gt - greater than (int, float)
# $gte - greater than or equal to (int, float)
# $lt - less than (int, float)
# $lte - less than or equal to (int, float)

print(collection.query(
    query_embeddings=[[11.1, 12.1, 13.1]],
    n_results=10,
    where={"chapter": {"$eq":"3"}}
))

print(collection.query(
    query_embeddings=[[11.1, 12.1, 13.1]],
    n_results=10,
    where={"chapter": {"$in":["3","29"]}}
))

# Chroma also supports an upsert operation, which updates existing items, or adds them if they don't yet exist.

collection.upsert(
    ids=["id1", "id2", "id3"],
    embeddings=[[1.1, 2.3, 3.2], [4.5, 6.9, 4.4], [1.1, 2.3, 3.2],],
    metadatas=[{"chapter": "3", "verse": "16"}, {"chapter": "3", "verse": "5"}, {"chapter": "29", "verse": "11"}],
    documents=["doc1", "doc2", "doc3",],
)

# to delete certain items using filters and ids

print(collection.delete(
    ids=["id1", "id2", "id3"],
	where={"chapter": "20"}
))

print(collection.get(
	ids=["id1", "id2", "id3"]
))

print(collection.delete(
    ids=["id1", "id2", "id3"],
	  where={"verse": "5"}
))

print(collection.get(
	ids=["id1", "id2", "id3"]
))